package com.learn.java.junit5.service;

import java.util.List;

import com.learn.java.junit5.collection.Employee;

public interface EmployeeService {

	public Employee saveEmployee(Employee employee);

	public Employee getEmployee(String id);

	public Employee updateEmployee(String id, String name);

	public String deleteEmployee(String id);

	public List<Employee> getEmployeeBySalaryBetween(Float minSalary, Float maxSalary);

	public void testAutogeneratedAPIs();

	public void testDeclAPIs();

	public void testDeclAPIsWithQuery();

	public String getWelcomeMessage();

}
