package com.learn.java.junit5.repository;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import com.learn.java.junit5.collection.Employee;

@Repository
public interface EmployeeAutogeneratedRepository extends MongoRepository<Employee, String> {

}
